version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@11ty/eleventy"
    versions:
    - 0.11.1
  - dependency-name: lodash
    versions:
    - 4.17.20
